# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers :
        default :
            web_path : ~

    twig:
        mode: lazy

    filter_sets :
        cache : ~

        # the name of the "filter set"
        post_image :

            # adjust the image quality to 75%
            quality : 75

            # list of transformations to apply (the "filters")
            filters :

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [960, 640], mode : outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
#                background : { size : [124, 94], position : center, color : '#000000' }

        single_post_image:
            quality: 75
            filters:
                thumbnail: { size: [1000, 515], mode: outbound }

        paiement_method_thumbnail:
            quality: 100
            filters:
                thumbnail: { size: [72, 48], mode: outbound }

        long_banner:
            quality: 75
            filters:
                thumbnail: { size: [1000, 350], mode: outbound }

        recent_post_image:
            quality: 100
            filters:
                thumbnail: { size: [570, 380], mode: outbound }

        about_us_image:
            quality: 75
            filters:
                thumbnail: { size: [1200, 797], mode: outbound }

        about_us_banner:
            quality: 75
            filters:
                thumbnail: { size: [1062, 590], mode: outbound }

        context_banner:
            quality: 75
            filters:
                thumbnail: { size: [1536, 1012], mode: outbound }

        profile_image_on_team_view:
            quality: 75
            filters:
                thumbnail: { size: [395, 480], mode: outbound }
                auto-rotate: ~