<?php

namespace App\Controller\Admin;

use App\Entity\Post;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Vich\UploaderBundle\Form\Type\VichImageType;

class PostCrudController extends AbstractCrudController
{
    public const UPLOAD_POST_BASE_PATH = 'images/upload/post';
    public const UPLOAD_POST_ROOT_PATH = 'public/images/upload/post';


    public static function getEntityFqcn(): string
    {
        return Post::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return parent::configureCrud($crud)
            ->setPageTitle('index', 'Publications Du Blog')
            ->setPageTitle('new', 'Publier un Post')
            ->setSearchFields(['title', 'content', 'author'])
            ->setDateFormat('medium')
            ->setTimeFormat('medium'); // TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id')->hideOnForm(),
            TextField::new('title', 'Titre'),
            TextField::new('slug', 'Slug')
                ->hideOnForm(),
            TextField::new('imageFile', 'Illustration')
                ->hideOnIndex()
                ->setFormType(VichImageType::class),
            ImageField::new('image', 'Image du post')
                ->hideOnForm()
                ->setBasePath(self::UPLOAD_POST_BASE_PATH)
                ->setUploadDir(self::UPLOAD_POST_ROOT_PATH)
                ->setSortable(false),
            TextEditorField::new('content', 'Contenu de l\'article'),
        ];
    }

}
